spring.application.name=sms
spring.datasource.url=jdbc:mysql://localhost:3306/student_management
spring.datasource.username=root
spring.datasource.password=Ankit@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret = my-new-secret-key-abababab-ababab-baabbab-abababab
spring.security.oauth2.client.registration.google.client-id  = 162152506434-rf0tiecias65hitappmkkm4s1kam90ls.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret = 